### ISSUE TITLE
Budget Bar

### ISSUE THREAD

**Issue by ScherwinBidar** [ScherwinBidar/capstone-project#1]
**Value Preposition**

As a User i need to see my expenses, so i can control my finances. 

**Description**

A div will be created. Inside this div, there is 1  components.  This component shows the date, the amount and the purchased item. This component is interactive, so it give the user the ability to create several bars with purchased items and infos about date and costs.

The user cannot input anything yet, because there won't be an input button, the only way to input that, is to hardcode that in the app itself through the components. However, that will be fixed with later user story's.

<img width="471" alt="Bildschirmfoto 2022-03-24 um 01 37 33" src="https://user-images.githubusercontent.com/85336025/159829334-d21faf05-045f-4bac-9b13-f513ab856ad8.png">

**Acceptance Criteria**

- [x]  A bar is created, which allows the User to see his spending, the item and the date for future expenses.
- [x] It has a basic styling.

**Tasks**

- [x] create next app and push repository
- [x] create basic div
- [x] create 1 component
- [x] shows date
- [x] shows item
- [x] shows amount
- [x] create basic css for every div and component
