### ISSUE TITLE
Wrapper div for Budget Bar

### ISSUE THREAD

**Issue by ScherwinBidar** [ScherwinBidar/capstone-project#4]
**Value Preposition**

As a User i need to have a field where more budget bars a deployed so i can see them all correctly.

**Description**

Create a basic div, where all the budget bars will be deployed when they are created.

This is important for the organization of the budget bars.

**Acceptance Criteria**

- [x]  create a div, which is a wrapper, where all the task bars can me deployed
- [x] It has a basic styling.

**Tasks**

- [x] create basic div
- [x] style that basic div 
- [x] style is responsive
