### ISSUE TITLE
Budget Date

### ISSUE THREAD

**Issue by ScherwinBidar** [ScherwinBidar/capstone-project#5]
**Value Preposition**

As a User i need to see the date formatted correctly, so i know when i did the purchase.

**Description**

The date div will be formatted correctly. For that, a new component will be created, called ,,Budget Date". That component will be nested in the ,,Budget Bar" component.

**Acceptance Criteria**

- [x]  date is formatted correctly
- [x] It has a basic styling and is responsive

**Tasks**

- [x] create new component ,, Budget Date"
- [x] format date correctly
- [x] style that component responsive
