### ISSUE TITLE
Interactive Budgetbar

### ISSUE THREAD

**Issue by ScherwinBidar** [ScherwinBidar/capstone-project#8]
**Value Preposition**

As a User i need to have a button, where i can input my date, item and the amount i purchased.

**Description**

create a new button ,,Neue Ausgabe" which allows the user to input the crucial informations.

**Acceptance Criteria**

- [x] User sees a button ,,Neue Ausgabe"
- [x] User can input his informations
- [x] has css style

**Tasks**

- [x] create a button ,, Neue Ausgabe"
- [x] create an input field, which has input, amount and date
- [x] create css and make it responsive
